services:
  - type: web
    name: trustscore-backend
    runtime: node
    rootDir: back-end
    plan: free
    buildCommand: npm install --include=dev ; npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
